export const PROFFESSIONAL_SECTION = {
  SPECIALTIES: [
    { id: 1, name: 'Acute Care' },
    { id: 2, name: 'Allergy and Asthma' },
    { id: 3, name: 'Ambulatory Care' },
    { id: 4, name: 'Anesthesiology' },
    { id: 5, name: 'Cardiology' },
    { id: 6, name: 'Case Management' },
    { id: 7, name: 'Chemical Dependency' },
    { id: 8, name: 'Correctional Nursing' },
    { id: 9, name: 'Critical Care' },
    { id: 10, name: 'Dermatology' },
    { id: 11, name: 'Disabilities' },
    { id: 12, name: 'Educational/Research' },
    { id: 13, name: 'Emergency/Trauma' },
    { id: 14, name: 'Endocrinology' },
    { id: 15, name: 'Family' },
    { id: 16, name: 'Forensic' },
    { id: 17, name: 'Gastroenterology' },
    { id: 18, name: 'Geriatrics' },
    { id: 19, name: 'Hematology / Oncology' },
    { id: 20, name: 'Holistic Nursing' },
    { id: 21, name: 'Home Health' },
    { id: 22, name: 'Hospice / Palliative' },
    { id: 23, name: 'Infection Control / Infectious Disease' },
    { id: 24, name: 'Informatics' },
    { id: 25, name: 'Infusion / Vascular' },
    { id: 26, name: 'Long Term Care' },
    { id: 27, name: 'Management/Admin/Leadership' },
    { id: 28, name: 'Medical/Surgical' },
    { id: 29, name: 'Mental Health' },
    { id: 30, name: 'Neonatal' },
    { id: 31, name: 'Nephrology' },
    { id: 32, name: 'Neurology' },
    { id: 33, name: 'Nursing Student' },
    { id: 34, name: 'OB/GYN/L&D' },
    { id: 35, name: 'Occupational/Public Health' },
    { id: 36, name: 'Orthopedics' },
    { id: 37, name: 'Other' },
    { id: 38, name: 'Pain Management' },
    { id: 39, name: 'Pediatrics' },
    { id: 40, name: 'Perianesthesia' },
    { id: 41, name: 'Perioperative' },
    { id: 42, name: 'Professional Development' },
    { id: 43, name: 'Psychiatric' },
    { id: 44, name: 'Pulmonary' },
    { id: 45, name: 'Quality / Risk Management' },
    { id: 46, name: 'Radiology' },
    { id: 47, name: 'Rehabilitation' },
    { id: 48, name: 'School Health' },
    { id: 49, name: 'Telemetry' },
    { id: 50, name: 'Urgent Care' },
    { id: 51, name: 'Urology' },
    { id: 52, name: "Women's Health" },
    { id: 53, name: 'Wound Care' },
  ],
  EDUCATION_LEVELS: [
    'Associate Degree',
    "Bachelor's Degree",
    "Master's Degree",
    'Doctoral Degree',
  ],
  CERTIFICATION_AGENCIES: [
    { id: 'AACN', label: 'AACN' },
    { id: 'ANA', label: 'ANA' },
    { id: 'ANCC', label: 'ANCC' },
    { id: 'NCC', label: 'NCC' },
    { id: 'NCCPA', label: 'NCCPA' },
    { id: 'ONCC', label: 'ONCC' },
    { id: 'PNCB', label: 'PNCB' },
    { id: 'OTHER', label: 'Other' },
  ],
};
