export const PROFFESSIONAL_SECTION = {
  SPECIALTIES: [
    { id: 1, name: 'Acute Care' },
    { id: 2, name: 'Allergy and Asthma' },
    { id: 3, name: 'Ambulatory Care' },
    { id: 4, name: 'Anesthesiology' },
    { id: 5, name: 'Cardiology' },
    { id: 6, name: 'Case Management' },
    { id: 7, name: 'Chemical Dependency' },
    { id: 8, name: 'Correctional Nursing' },
    { id: 9, name: 'Critical Care' },
    { id: 10, name: 'Dermatology' },
    { id: 11, name: 'Disabilities' },
    { id: 12, name: 'Educational/Research' },
    { id: 13, name: 'Emergency/Trauma' },
    { id: 14, name: 'Endocrinology' },
    { id: 15, name: 'Family' },
    { id: 16, name: 'Forensic' },
    { id: 17, name: 'Gastroenterology' },
    { id: 18, name: 'Geriatrics' },
    { id: 19, name: 'Hematology / Oncology' },
    { id: 20, name: 'Holistic Nursing' },
    { id: 21, name: 'Home Health' },
    { id: 22, name: 'Hospice / Palliative' },
    { id: 23, name: 'Infection Control / Infectious Disease' },
    { id: 24, name: 'Informatics' },
    { id: 25, name: 'Infusion / Vascular' },
    { id: 26, name: 'Long Term Care' },
    { id: 27, name: 'Management/Admin/Leadership' },
    { id: 28, name: 'Medical/Surgical' },
    { id: 29, name: 'Mental Health' },
    { id: 30, name: 'Neonatal' },
    { id: 31, name: 'Nephrology' },
    { id: 32, name: 'Neurology' },
    { id: 33, name: 'Nursing Student' },
    { id: 34, name: 'OB/GYN/L&D' },
    { id: 35, name: 'Occupational/Public Health' },
    { id: 36, name: 'Orthopedics' },
    { id: 37, name: 'Other' },
    { id: 38, name: 'Pain Management' },
    { id: 39, name: 'Pediatrics' },
    { id: 40, name: 'Perianesthesia' },
    { id: 41, name: 'Perioperative' },
    { id: 42, name: 'Professional Development' },
    { id: 43, name: 'Psychiatric' },
    { id: 44, name: 'Pulmonary' },
    { id: 45, name: 'Quality / Risk Management' },
    { id: 46, name: 'Radiology' },
    { id: 47, name: 'Rehabilitation' },
    { id: 48, name: 'School Health' },
    { id: 49, name: 'Telemetry' },
    { id: 50, name: 'Urgent Care' },
    { id: 51, name: 'Urology' },
    { id: 52, name: "Women's Health" },
    { id: 53, name: 'Wound Care' },
  ],
  EDUCATION_LEVELS: [
    'Associate Degree',
    "Bachelor's Degree",
    "Master's Degree",
    'Doctoral Degree',
  ],
  CERTIFICATION_AGENCIES: [
    { id: 'AACN', label: 'AACN' },
    { id: 'ANA', label: 'ANA' },
    { id: 'ANCC', label: 'ANCC' },
    { id: 'NCC', label: 'NCC' },
    { id: 'NCCPA', label: 'NCCPA' },
    { id: 'ONCC', label: 'ONCC' },
    { id: 'PNCB', label: 'PNCB' },
    { id: 'OTHER', label: 'Other' },
  ],
  US_STATES: [
    'ALABAMA',
    'ALASKA',
    'ARIZONA',
    'ARKANSAS',
    'CALIFORNIA',
    'COLORADO',
    'CONNECTICUT',
    'DELAWARE',
    'FLORIDA',
    'GEORGIA',
    'HAWAII',
    'IDAHO',
    'ILLINOIS',
    'INDIANA',
    'IOWA',
    'KANSAS',
    'KENTUCKY',
    'LOUISIANA',
    'MAINE',
    'MARYLAND',
    'MASSACHUSETTS',
    'MICHIGAN',
    'MINNESOTA',
    'MISSISSIPPI',
    'MISSOURI',
    'MONTANA',
    'NEBRASKA',
    'NEVADA',
    'NEW HAMPSHIRE',
    'NEW JERSEY',
    'NEW MEXICO',
    'NEW YORK',
    'NORTH CAROLINA',
    'NORTH DAKOTA',
    'OHIO',
    'OKLAHOMA',
    'OREGON',
    'PENNSYLVANIA',
    'RHODE ISLAND',
    'SOUTH CAROLINA',
    'SOUTH DAKOTA',
    'TENNESSEE',
    'TEXAS',
    'UTAH',
    'VERMONT',
    'VIRGINIA',
    'WASHINGTON',
    'WEST VIRGINIA',
    'WISCONSIN',
    'WYOMING',
  ],
  MEMBERSHIPS: [
    'AACN',
    'AANA',
    'AANN',
    'AAOHN',
    'AAPA',
    'AHNA',
    'AMSN',
    'ANA',
    'ANA District',
    'ANNA',
    'ANPD',
    'AONE',
    'AONL',
    'AORN',
    'APNA',
    'APRN',
    'ARIN',
    'ARN',
    'ASPAN',
    'ASPMN',
    'AVA',
    'CNLA',
    'CNS',
    'DDNA',
    'DNA',
    'ENA',
    'HPNA',
    'IAFN',
    'INS',
    'ITNS',
    'NACNS',
    'NAHN',
    'NANN',
    'NASN',
    'NBNA',
    'NLN',
    'NSNA',
    'ONS',
    'PCNA',
    'SGNA',
    'SNA',
    'STTI',
    'SUNA',
    'WOCN',
  ],
  INCOME_LEVEL_LABELS: [
    'Less than $30,000',
    '$30,000 - $40,000',
    '$40,000 - $50,000',
    '$50,000 - $60,000',
    '$60,000 - $70,000',
    '$70,000 - $80,000',
    '$80,000 - $90,000',
    '$90,000 - $100,000',
    'More than $100,000',
  ],
};
